//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Web.StoreWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StoreWS.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento filePath no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportFile", ReplyAction="*")]
        Store.Web.StoreWS.ImportFileResponse ImportFile(Store.Web.StoreWS.ImportFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportFile", ReplyAction="*")]
        System.Threading.Tasks.Task<Store.Web.StoreWS.ImportFileResponse> ImportFileAsync(Store.Web.StoreWS.ImportFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportFile", Namespace="http://tempuri.org/", Order=0)]
        public Store.Web.StoreWS.ImportFileRequestBody Body;
        
        public ImportFileRequest() {
        }
        
        public ImportFileRequest(Store.Web.StoreWS.ImportFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filePath;
        
        public ImportFileRequestBody() {
        }
        
        public ImportFileRequestBody(string filePath) {
            this.filePath = filePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public Store.Web.StoreWS.ImportFileResponseBody Body;
        
        public ImportFileResponse() {
        }
        
        public ImportFileResponse(Store.Web.StoreWS.ImportFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ImportFileResponseBody {
        
        public ImportFileResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Store.Web.StoreWS.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Store.Web.StoreWS.ServiceSoap>, Store.Web.StoreWS.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Store.Web.StoreWS.ImportFileResponse Store.Web.StoreWS.ServiceSoap.ImportFile(Store.Web.StoreWS.ImportFileRequest request) {
            return base.Channel.ImportFile(request);
        }
        
        public void ImportFile(string filePath) {
            Store.Web.StoreWS.ImportFileRequest inValue = new Store.Web.StoreWS.ImportFileRequest();
            inValue.Body = new Store.Web.StoreWS.ImportFileRequestBody();
            inValue.Body.filePath = filePath;
            Store.Web.StoreWS.ImportFileResponse retVal = ((Store.Web.StoreWS.ServiceSoap)(this)).ImportFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Store.Web.StoreWS.ImportFileResponse> Store.Web.StoreWS.ServiceSoap.ImportFileAsync(Store.Web.StoreWS.ImportFileRequest request) {
            return base.Channel.ImportFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Store.Web.StoreWS.ImportFileResponse> ImportFileAsync(string filePath) {
            Store.Web.StoreWS.ImportFileRequest inValue = new Store.Web.StoreWS.ImportFileRequest();
            inValue.Body = new Store.Web.StoreWS.ImportFileRequestBody();
            inValue.Body.filePath = filePath;
            return ((Store.Web.StoreWS.ServiceSoap)(this)).ImportFileAsync(inValue);
        }
    }
}
